### ISSUE TITLE
Cite this box - removal

### ISSUE THREAD

**Issue by emilyfildes** [TheScienceMuseum/collectionsonline#625] opened 2016-11-29 11:37 UTC
Hello,

Please could we suppress the 'Cite this box' on:
- All people records
- All archive records

Thanks very much,
Emily

**Comment by jamieu** [comment] 2016-11-29 16:01
Duplicate of https://github.com/TheScienceMuseum/collectionsonline/issues/611

**Closed by jamieu** 2016-11-29 16:01 UTC
Labels: enhancement, Key for launch, priority-2
